# Generated by Django 3.0.6 on 2020-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topText', models.TextField()),
                ('topTextSize', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bottomText', models.TextField()),
                ('bottomTextSize', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temp', models.ImageField(upload_to='memes/')),
            ],
        ),
    ]
